### ISSUE TITLE
Terminal object has no attribute

### ISSUE THREAD

**Issue by llmaboi** [ty-porter/RGBMatrixEmulator#21]
Sorry if this is something trivial, I have very little, by that meaning almost no experience in python.

After I have tried installing `g++, make, python3, python3-pip, ipython, git` installed `pip3 install --upgrade setuptools` then in the main directory I ran `sudo python3 setup.py install`.

Now trying to run `python3 rotating-block-generator.py` causes the following error.

``` python
sh: 1: mode: not found
Traceback (most recent call last):
  File "/home/user/last-fm-display/vendor/RGBMatrixEmulator/samples/rotating-block-generator.py", line 71, in <module>
    if (not rotating_block_generator.process()):
  File "/home/user/last-fm-display/vendor/RGBMatrixEmulator/samples/samplebase.py", line 75, in process
    self.run()
  File "/home/user/last-fm-display/vendor/RGBMatrixEmulator/samples/rotating-block-generator.py", line 65, in run
    offset_canvas = self.matrix.SwapOnVSync(offset_canvas)
  File "/usr/local/lib/python3.9/dist-packages/RGBMatrixEmulator-0.5.1-py3.9.egg/RGBMatrixEmulator/emulators/matrix.py", line 21, in SwapOnVSync
    canvas.check_for_quit_event()
  File "/usr/local/lib/python3.9/dist-packages/RGBMatrixEmulator-0.5.1-py3.9.egg/RGBMatrixEmulator/emulators/canvas.py", line 52, in check_for_quit_event
    self.display_adapter.check_for_quit_event()
AttributeError: 'Terminal' object has no attribute 'check_for_quit_event'
```

**Comment by ty-porter** [comment]
There was a typo in the base adapter class that affects everything except pygame, so this is now fixed in release 0.5.2

Thanks for the report!
