### ISSUE TITLE
No available video device

### ISSUE THREAD

**Issue by llmaboi** [ty-porter/RGBMatrixEmulator#23]
I've updated to your current branch, if I try to run the example of `image-viewer.py` I'll get the no available video device error. I changed the `display_adapter` property in the emulator config from pygame to terminal and back with no success.

``` shell
$ python3 vendor/RGBMatrixEmulator/samples/image-viewer.py images/cover.jpg
EMULATOR: Loading RGBME v0.5.2 - 32x32 Matrix | 1x1 Chain | 16px per LED (SQUARE)
Traceback (most recent call last):
  File "/home/my_dir/vendor/RGBMatrixEmulator/samples/image-viewer.py", line 27, in <module>
    matrix.SetImage(image.convert('RGB'))
  File "/usr/local/lib/python3.9/dist-packages/RGBMatrixEmulator-0.5.2-py3.9.egg/RGBMatrixEmulator/emulators/matrix.py", line 42, in SetImage
    self.__sync_canvas()
  File "/usr/local/lib/python3.9/dist-packages/RGBMatrixEmulator-0.5.2-py3.9.egg/RGBMatrixEmulator/emulators/matrix.py", line 48, in __sync_canvas
    self.canvas = Canvas(options = self.options)
  File "/usr/local/lib/python3.9/dist-packages/RGBMatrixEmulator-0.5.2-py3.9.egg/RGBMatrixEmulator/emulators/canvas.py", line 14, in __init__
    self.display_adapter.load_emulator_window()
  File "/usr/local/lib/python3.9/dist-packages/RGBMatrixEmulator-0.5.2-py3.9.egg/RGBMatrixEmulator/adapters/pygame.py", line 23, in load_emulator_window
    self.__surface = pygame.display.set_mode(self.options.window_size())
pygame.error: No available video device
```

**Comment by llmaboi** [comment]
Ignore me you have to be in the `samples` directory sorry for creating the ticket before checking that.
